"""Open a GitHub PR from fixer output.

Flow:
  1. Detect repo owner/name from `git remote get-url origin`
  2. Create a fresh branch `aicritic/fix-<timestamp>` from current HEAD
  3. Stage the files the fixer rewrote, commit, push
  4. POST /repos/{owner}/{repo}/pulls via the REST API using GITHUB_TOKEN

Falls back with a clear error message if any step fails — the caller can
still rely on local fixes having been written."""
import json
import os
import re
import subprocess
import urllib.request
import urllib.error
from datetime import datetime
from typing import Optional


class PRError(RuntimeError):
    pass


def _run(args: list, cwd: str) -> str:
    try:
        r = subprocess.run(
            ["git"] + args, cwd=cwd, check=True, capture_output=True, text=True
        )
        return r.stdout
    except FileNotFoundError as e:
        raise PRError("git is not installed") from e
    except subprocess.CalledProcessError as e:
        raise PRError(
            f"git {' '.join(args)} failed: {e.stderr.strip() or e.stdout.strip()}"
        ) from e


def _repo_root(start: str) -> str:
    return _run(["rev-parse", "--show-toplevel"], cwd=start).strip()


def _parse_owner_repo(remote_url: str) -> tuple:
    """Accept both https and ssh remote URLs."""
    # git@github.com:owner/repo(.git)?
    m = re.match(r"(?:git@[^:]+:|https?://[^/]+/)([^/]+)/([^/.]+)", remote_url.strip())
    if not m:
        raise PRError(f"Could not parse owner/repo from remote URL: {remote_url}")
    return m.group(1), m.group(2)


def _api_host(remote_url: str) -> str:
    """github.com → api.github.com; GHES host.example.com → host.example.com/api/v3."""
    m = re.match(r"(?:git@([^:]+):|https?://([^/]+)/)", remote_url.strip())
    if not m:
        return "api.github.com"
    host = m.group(1) or m.group(2)
    return "api.github.com" if host == "github.com" else f"{host}/api/v3"


def _base_branch(cwd: str) -> str:
    """Return the remote HEAD branch, or fall back to 'main'."""
    try:
        ref = _run(["symbolic-ref", "refs/remotes/origin/HEAD"], cwd).strip()
        return ref.split("/")[-1] if ref else "main"
    except PRError:
        return "main"


def open_pr_from_fixes(
    fixer_result: dict,
    target: str,
    tool_label: str,
    token: str,
    summary: str = "",
) -> str:
    """Create branch, commit, push, open PR. Returns the PR URL."""
    if not token:
        raise PRError("GITHUB_TOKEN not set — cannot open PR")

    fixed = fixer_result.get("files", []) + [
        {"path": f["path"]} for f in fixer_result.get("applied_literal", [])
    ]
    paths = sorted({f["path"] for f in fixed})
    if not paths:
        raise PRError("No files were modified — nothing to open a PR for")

    start = target if os.path.isdir(target) else os.path.dirname(target) or "."
    repo_dir = _repo_root(start)

    remote = _run(["remote", "get-url", "origin"], repo_dir).strip()
    owner, repo = _parse_owner_repo(remote)
    api_host = _api_host(remote)
    base = _base_branch(repo_dir)

    timestamp = datetime.now().strftime("%Y%m%d-%H%M%S")
    branch = f"aicritic/fix-{tool_label}-{timestamp}"

    _run(["checkout", "-b", branch], repo_dir)
    for p in paths:
        rel = os.path.relpath(p, repo_dir)
        _run(["add", "--", rel], repo_dir)

    commit_msg = f"aicritic: auto-fix ({tool_label})\n\n{summary or fixer_result.get('summary', '')}"
    _run(["commit", "-m", commit_msg], repo_dir)
    _run(["push", "-u", "origin", branch], repo_dir)

    pr_title = f"aicritic auto-fix: {tool_label}"
    pr_body = (
        f"Automated fix generated by aicritic.\n\n"
        f"**Tool:** `{tool_label}`\n"
        f"**Files changed:** {len(paths)}\n\n"
        f"### Summary\n{summary or fixer_result.get('summary') or '(no summary)'}\n\n"
        f"### Changes applied\n"
        + "\n".join(f"- `{os.path.relpath(p, repo_dir)}`" for p in paths)
        + "\n\n> Review each change before merging. "
        "aicritic's fixer is deterministic for literal patches but LLM-assisted "
        "for anything ambiguous."
    )

    url = f"https://{api_host}/repos/{owner}/{repo}/pulls"
    payload = json.dumps({
        "title": pr_title,
        "body":  pr_body,
        "head":  branch,
        "base":  base,
    }).encode("utf-8")
    req = urllib.request.Request(
        url,
        data=payload,
        method="POST",
        headers={
            "Authorization": f"Bearer {token}",
            "Accept": "application/vnd.github+json",
            "X-GitHub-Api-Version": "2022-11-28",
            "Content-Type": "application/json",
            "User-Agent": "aicritic",
        },
    )
    try:
        with urllib.request.urlopen(req, timeout=30) as resp:
            data = json.loads(resp.read())
    except urllib.error.HTTPError as e:
        detail = e.read().decode("utf-8", errors="replace")[:500]
        raise PRError(f"GitHub API returned {e.code}: {detail}") from e
    except urllib.error.URLError as e:
        raise PRError(f"Could not reach GitHub API: {e.reason}") from e

    return data.get("html_url", f"(PR created but URL missing — branch {branch})")
