"""Test Generation stage — writes runnable tests for high-risk uncovered code.

Strategy:
  1. Detect the project's test framework from imports in source files.
  2. Identify the intersection of critic findings and coverage gaps — these are
     the highest-priority targets (high-risk code with no tests).
  3. Call Claude Sonnet (cached) to generate complete, runnable tests using the
     project's real class/function names and realistic inputs that would
     actually catch the vulnerability.
  4. Track overall coverage across runs in .aicritic-coverage-history.json and
     compute per-file deltas.
  5. Write tests to a file with a guard comment — never auto-committed.

Output schema:
    {
        "framework":         str,           # "pytest" | "unittest" | "jest" | ...
        "targets":           list[dict],    # high-risk uncovered paths found
        "tests":             list[dict],    # generated test cases
        "output_file":       str | None,
        "overall_coverage":  float | None,  # current run % (or None if no cov data)
        "prev_coverage":     float | None,  # previous run %
        "coverage_delta":    float | None,  # positive = improved
        "per_file_delta":    dict,          # {filename: {"prev":x, "curr":y, "delta":z}}
        "policy_violation":  bool,
        "policy_floor":      int | None,
        "summary":           str,
    }
"""
from __future__ import annotations

import json
import os
import re
import textwrap
from datetime import datetime, timezone
from typing import Optional

from openai import OpenAI
import config
from pipeline import parse_llm_json
from pipeline.result_cache import get as cache_get, put as cache_put

HISTORY_FILE = ".aicritic-coverage-history.json"
GENERATED_HEADER = "# generated by aicritic — review before committing\n"

_FRAMEWORK_SIGNATURES: dict[str, list[str]] = {
    "pytest":    ["import pytest", "from pytest import", "@pytest.fixture", "@pytest.mark"],
    "unittest":  ["import unittest", "from unittest import", "unittest.TestCase"],
    "jest":      ["import jest", "from jest", "describe(", "it(", "test(", "expect("],
    "mocha":     ["import mocha", "require('mocha')", "require(\"mocha\")", "describe("],
    "vitest":    ["import vitest", "from vitest", "vi.fn("],
    "go_test":   ["\"testing\"", "func Test"],
    "junit":     ["import org.junit", "@Test", "import junit"],
    "rspec":     ["require 'rspec'", "describe ", "RSpec.describe"],
    "xunit":     ["using Xunit", "[Fact]", "[Theory]"],
    "minitest":  ["require 'minitest'", "class.*Minitest::Test"],
}

_FRAMEWORK_DEFAULTS: dict[str, str] = {
    "python":     "pytest",
    "javascript": "jest",
    "typescript": "jest",
    "go":         "go_test",
    "java":       "junit",
    "ruby":       "rspec",
    "csharp":     "xunit",
    "rust":       "rust_test",
}

_FRAMEWORK_EXT: dict[str, str] = {
    "pytest":    "_test.py",
    "unittest":  "_test.py",
    "jest":      ".test.ts",
    "mocha":     ".test.js",
    "vitest":    ".test.ts",
    "go_test":   "_test.go",
    "junit":     "Test.java",
    "rspec":     "_spec.rb",
    "xunit":     "Tests.cs",
    "rust_test": "_test.rs",
    "minitest":  "_test.rb",
}

_SYSTEM_PROMPT = """\
You are an expert test engineer. Your task is to generate complete, runnable tests \
for high-risk code paths that currently have no test coverage.

Rules — follow every one precisely:
1. Use ONLY the exact class/function/method names from the source code.  Never invent names.
2. Inputs must be REALISTIC values derived from the actual code logic — not "foo", "bar", 1, 2.
3. Every assertion must FAIL if the vulnerability exists and PASS when the code is fixed.
   Never write `assert True`, `pass`, or a stub body.
4. One test function per finding.  Name it: `test_<function>_<short_vulnerability_slug>`.
5. Add a one-line comment above each assert explaining what it verifies.
6. Do NOT add imports that are not needed.  Do NOT wrap in a class unless the framework requires it.
7. Output valid JSON only (no prose, no markdown fences) following this schema:

{
  "framework": "<detected framework>",
  "tests": [
    {
      "target_file": "<source file the test covers>",
      "target_function": "<exact function/method name>",
      "finding_risk": "high" | "critical",
      "finding_description": "<one-line description of the vulnerability>",
      "test_function_name": "test_<name>",
      "test_code": "<complete, runnable test function as a string>",
      "explanation": "<one sentence: what this test proves>"
    }
  ],
  "suggested_filename": "<e.g. tests/test_auth.py>",
  "summary": "<one sentence: what was generated>"
}
"""


# ---------------------------------------------------------------------------
# Framework detection
# ---------------------------------------------------------------------------

def detect_framework(inputs: dict) -> str:
    """Detect the test framework from source file content and language."""
    all_text = "\n".join(f["content"] for f in inputs["files"])
    lang = _dominant_language(inputs)

    for framework, sigs in _FRAMEWORK_SIGNATURES.items():
        for sig in sigs:
            if sig in all_text:
                return framework

    return _FRAMEWORK_DEFAULTS.get(lang, "pytest")


def _dominant_language(inputs: dict) -> str:
    counts: dict[str, int] = {}
    for f in inputs["files"]:
        lang = f.get("language", "python")
        counts[lang] = counts.get(lang, 0) + 1
    return max(counts, key=counts.get) if counts else "python"


# ---------------------------------------------------------------------------
# Coverage gap × finding intersection
# ---------------------------------------------------------------------------

def _parse_line_range(line_range: str) -> set[int]:
    """Parse '42-57' or '42' → set of ints."""
    lines: set[int] = set()
    if not line_range:
        return lines
    for part in str(line_range).split(","):
        part = part.strip()
        if "-" in part:
            try:
                lo, hi = part.split("-", 1)
                lines.update(range(int(lo), int(hi) + 1))
            except ValueError:
                pass
        else:
            try:
                lines.add(int(part))
            except ValueError:
                pass
    return lines


def find_uncovered_high_risk(inputs: dict, critic_result: dict) -> list[dict]:
    """Return findings where the flagged lines have no coverage.

    If no coverage data is available, returns all HIGH/CRITICAL findings
    (they're worth testing regardless).
    """
    coverage: dict = inputs.get("coverage") or {}
    findings = critic_result.get("findings", [])
    high_risk = [
        f for f in findings
        if f.get("risk", "low") in ("high", "critical")
    ]

    if not coverage:
        # No coverage data — return all high-risk findings as targets
        return [
            {**f, "_coverage_gap": None, "_coverage_rate": None}
            for f in high_risk
        ]

    targets = []
    for finding in high_risk:
        fpath = finding.get("file", "")
        # Try to match coverage key (may be relative or absolute)
        cov_data = _lookup_coverage(coverage, fpath)
        if cov_data is None:
            # File has no coverage entry — treat as uncovered
            targets.append({**finding, "_coverage_gap": "no coverage data", "_coverage_rate": 0.0})
            continue

        missing = set(cov_data.get("missing_lines", []))
        finding_lines = _parse_line_range(finding.get("line_range", ""))
        overlap = finding_lines & missing

        if overlap or not finding_lines:
            targets.append({
                **finding,
                "_coverage_gap": sorted(overlap) or list(missing)[:5],
                "_coverage_rate": cov_data.get("line_rate", 0.0) * 100,
            })

    return targets


def _lookup_coverage(coverage: dict, fpath: str) -> Optional[dict]:
    """Try several path normalisations to find a coverage entry."""
    candidates = [
        fpath,
        os.path.basename(fpath),
        fpath.lstrip("./"),
        os.path.normpath(fpath),
    ]
    for key in coverage:
        norm_key = os.path.normpath(key)
        for c in candidates:
            if norm_key == os.path.normpath(c) or key.endswith(c) or c.endswith(key):
                return coverage[key]
    return None


# ---------------------------------------------------------------------------
# Coverage summary helpers
# ---------------------------------------------------------------------------

def _overall_coverage(inputs: dict) -> Optional[float]:
    """Compute average line-rate across all files with coverage data."""
    coverage = inputs.get("coverage") or {}
    if not coverage:
        return None
    rates = [v["line_rate"] for v in coverage.values() if "line_rate" in v]
    return (sum(rates) / len(rates)) * 100 if rates else None


def _per_file_coverage(inputs: dict) -> dict[str, float]:
    coverage = inputs.get("coverage") or {}
    return {
        k: round(v["line_rate"] * 100, 1)
        for k, v in coverage.items()
        if "line_rate" in v
    }


# ---------------------------------------------------------------------------
# Coverage history
# ---------------------------------------------------------------------------

def _load_history(target: str) -> list[dict]:
    path = os.path.join(os.path.dirname(os.path.abspath(target)) if os.path.isfile(target) else target,
                        HISTORY_FILE)
    if not os.path.exists(path):
        path = HISTORY_FILE
    try:
        with open(path, encoding="utf-8") as fh:
            return json.load(fh).get("runs", [])
    except (OSError, json.JSONDecodeError, ValueError):
        return []


def _save_history(target: str, run: dict) -> None:
    base = (os.path.dirname(os.path.abspath(target))
            if os.path.isfile(target) else target)
    path = os.path.join(base, HISTORY_FILE)
    try:
        runs = _load_history(target)
    except Exception:
        runs = []
    runs.append(run)
    # Keep last 50 runs
    runs = runs[-50:]
    try:
        with open(path, "w", encoding="utf-8") as fh:
            json.dump({"runs": runs}, fh, indent=2)
    except OSError:
        pass


def compute_coverage_delta(
    inputs: dict,
    target: str,
) -> tuple[Optional[float], Optional[float], Optional[float], dict]:
    """Compare current coverage against the last recorded run.

    Returns (current_pct, prev_pct, delta, per_file_delta).
    """
    current = _overall_coverage(inputs)
    per_file_curr = _per_file_coverage(inputs)

    runs = _load_history(target)

    prev: Optional[float] = None
    per_file_prev: dict[str, float] = {}
    if runs:
        last = runs[-1]
        prev = last.get("overall_coverage")
        per_file_prev = last.get("per_file", {})

    delta = (current - prev) if (current is not None and prev is not None) else None

    per_file_delta: dict = {}
    all_files = set(per_file_curr) | set(per_file_prev)
    for fname in all_files:
        curr_val = per_file_curr.get(fname)
        prev_val = per_file_prev.get(fname)
        per_file_delta[fname] = {
            "prev": prev_val,
            "curr": curr_val,
            "delta": round(curr_val - prev_val, 1) if (curr_val is not None and prev_val is not None) else None,
        }

    # Record this run
    if current is not None:
        _save_history(target, {
            "timestamp": datetime.now(timezone.utc).isoformat(),
            "target": str(target),
            "overall_coverage": round(current, 2),
            "per_file": per_file_curr,
        })

    return current, prev, delta, per_file_delta


# ---------------------------------------------------------------------------
# LLM test generation
# ---------------------------------------------------------------------------

def _build_user_message(inputs: dict, targets: list[dict], framework: str) -> str:
    """Build the prompt: source context for each target + task description."""
    lines: list[str] = [f"# Test Framework: {framework}\n"]

    # Source context — full files that appear in targets
    target_files = {t.get("file", "") for t in targets}
    for f in inputs["files"]:
        if f["path"] in target_files or os.path.basename(f["path"]) in {
            os.path.basename(p) for p in target_files
        }:
            lang = f.get("language", "python")
            lines.append(f"## Source: {f['path']}\n```{lang}\n{f['content']}\n```\n")

    lines.append("# High-Risk Uncovered Paths (generate tests for ALL of these)\n")
    for i, t in enumerate(targets, 1):
        gap = t.get("_coverage_gap")
        rate = t.get("_coverage_rate")
        cov_info = ""
        if rate is not None:
            cov_info = f" | file coverage: {rate:.0f}%"
        if gap:
            missing_str = ", ".join(str(x) for x in (gap if isinstance(gap, list) else [gap]))
            cov_info += f" | uncovered lines: {missing_str}"
        lines.append(
            f"{i}. [{t.get('risk','?').upper()}] {t.get('file','')}:{t.get('line_range','')}{cov_info}\n"
            f"   Finding: {t.get('description','')}\n"
        )

    lines.append(
        "\nGenerate one complete runnable test per finding. "
        "Use exact names from the source. Realistic inputs. "
        "Assertions must catch the actual vulnerability."
    )
    return "\n".join(lines)


def _empty(reason: str = "") -> dict:
    return {
        "framework": "unknown",
        "targets": [],
        "tests": [],
        "output_file": None,
        "overall_coverage": None,
        "prev_coverage": None,
        "coverage_delta": None,
        "per_file_delta": {},
        "policy_violation": False,
        "policy_floor": None,
        "summary": f"Test generator skipped: {reason}" if reason else "No high-risk targets found.",
    }


def run_test_generator(
    inputs: dict,
    critic_result: dict,
    target: str,
    output_file: Optional[str] = None,
    policy: Optional[dict] = None,
    token: Optional[str] = None,
    auto_commit: bool = False,
) -> dict:
    """Generate runnable tests for high-risk uncovered code paths.

    Args:
        inputs:       Loaded source files + optional coverage map.
        critic_result: Opus critic output with findings.
        target:       Target path (used for history file location).
        output_file:  Where to write generated tests (appends if exists).
        policy:       Parsed .aicritic-policy.yaml dict (for min_coverage).
        token:        GitHub PAT override.
        auto_commit:  Unused — guard against accidentally wiring this up.

    Returns:
        Result dict per module docstring schema.
    """
    # 1. Coverage tracking (always, even with no targets)
    current_cov, prev_cov, cov_delta, per_file_delta = compute_coverage_delta(inputs, target)

    # 2. Policy gate — coverage floor
    policy = policy or {}
    policy_floor = policy.get("min_coverage")
    policy_violation = False
    if policy_floor is not None and current_cov is not None:
        policy_violation = current_cov < float(policy_floor)

    # 3. Find high-risk uncovered targets
    framework = detect_framework(inputs)
    targets = find_uncovered_high_risk(inputs, critic_result)

    base: dict = {
        "framework": framework,
        "targets": targets,
        "tests": [],
        "output_file": output_file,
        "overall_coverage": round(current_cov, 2) if current_cov is not None else None,
        "prev_coverage": round(prev_cov, 2) if prev_cov is not None else None,
        "coverage_delta": round(cov_delta, 2) if cov_delta is not None else None,
        "per_file_delta": per_file_delta,
        "policy_violation": policy_violation,
        "policy_floor": policy_floor,
        "summary": "",
    }

    if not targets:
        base["summary"] = (
            "No high-risk uncovered paths found — nothing to generate."
            if inputs.get("coverage") else
            "No HIGH/CRITICAL findings — nothing to generate."
        )
        return base

    # 4. LLM call
    user_message = _build_user_message(inputs, targets, framework)
    cached = cache_get("test_generator", "sonnet", _SYSTEM_PROMPT, user_message)
    if cached is not None:
        cached.update(base)
        cached["_from_cache"] = True
    else:
        try:
            client = OpenAI(
                base_url=config.GITHUB_MODELS_BASE_URL,
                api_key=token or config.GITHUB_TOKEN,
            )
            response = client.chat.completions.create(
                model=config.MODELS.get("analyst", "claude-3-5-sonnet"),
                messages=[
                    {"role": "system", "content": _SYSTEM_PROMPT},
                    {"role": "user",   "content": user_message},
                ],
                max_tokens=config.MAX_TOKENS,
                temperature=0.1,  # Low temperature for deterministic code generation
            )
            llm_out = parse_llm_json(response.choices[0].message.content)
            cache_put("test_generator", "sonnet", _SYSTEM_PROMPT, user_message, llm_out)
        except Exception as e:
            base["summary"] = f"Test generation failed: {type(e).__name__}: {e}"
            return base

        cached = llm_out
        cached.update(base)

    # Normalise: the LLM result may have its own "tests" key
    tests = cached.get("tests") or llm_out.get("tests", [])
    base["tests"] = tests
    base["framework"] = cached.get("framework") or framework
    base["summary"] = cached.get("summary") or f"Generated {len(tests)} test(s) for {len(targets)} high-risk path(s)."

    # 5. Write to file
    if output_file and tests:
        _write_tests(tests, framework, output_file, cached.get("suggested_filename"))

    return base


# ---------------------------------------------------------------------------
# File writer
# ---------------------------------------------------------------------------

def _write_tests(
    tests: list[dict],
    framework: str,
    output_file: str,
    suggested_filename: Optional[str],
) -> None:
    """Append generated tests to output_file (creates if absent)."""
    # Determine final path
    path = output_file
    if os.path.isdir(path):
        fname = suggested_filename or f"test_aicritic_generated{_FRAMEWORK_EXT.get(framework, '_test.py')}"
        path = os.path.join(path, os.path.basename(fname))

    exists = os.path.exists(path)
    os.makedirs(os.path.dirname(os.path.abspath(path)), exist_ok=True)

    with open(path, "a" if exists else "w", encoding="utf-8") as fh:
        if not exists:
            fh.write(GENERATED_HEADER)
            fh.write(_framework_imports(framework))
        else:
            fh.write(f"\n\n{GENERATED_HEADER.strip()}\n")

        for t in tests:
            code = t.get("test_code", "")
            if not code:
                continue
            # Ensure the guard comment is on every generated block
            if "generated by aicritic" not in code:
                code = f"# generated by aicritic — {t.get('target_file','')}: {t.get('finding_description','')}\n{code}"
            fh.write("\n\n")
            fh.write(textwrap.dedent(code).strip())
            fh.write("\n")


def _framework_imports(framework: str) -> str:
    return {
        "pytest":    "import pytest\n\n",
        "unittest":  "import unittest\n\n",
        "jest":      "",
        "vitest":    "import { describe, it, expect } from 'vitest';\n\n",
        "go_test":   'import "testing"\n\n',
        "junit":     "import org.junit.jupiter.api.Test;\nimport static org.junit.jupiter.api.Assertions.*;\n\n",
        "rspec":     "require 'rspec'\n\n",
    }.get(framework, "")


# ---------------------------------------------------------------------------
# Coverage summary for console / reports
# ---------------------------------------------------------------------------

def coverage_trend_summary(result: dict) -> str:
    """One-line human-readable coverage trend string."""
    current = result.get("overall_coverage")
    delta   = result.get("coverage_delta")
    floor   = result.get("policy_floor")

    if current is None:
        return ""

    parts = [f"Coverage: {current:.1f}%"]
    if delta is not None:
        sign = "+" if delta >= 0 else ""
        parts.append(f"({sign}{delta:.1f}% this run)")
    if floor is not None:
        parts.append(f"[floor: {floor}%]")
    if result.get("policy_violation"):
        parts.append("⚠ BELOW FLOOR")
    return "  ".join(parts)
